import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from 'react'
import { Activity, Atom, Beaker, BookOpen, FlaskConical, Radio, Volume2, X } from 'lucide-react'
import { appendProjectEvents, createProjectEvent, deriveBranchState } from '../project/event-log'
import { chaosReportAnalysis, createDefaultChaosScenarios, runChaosTesting, type FroamChaosReport } from '../project/chaos'
import { readFroamLabsFlags, writeFroamLabsFlags, type FroamLabsFlags } from '../project/experiments'
import { applyInteractionRecipe, deleteInteractionRecipe, previewInteractionRecipe, saveInteractionRecipe, searchInteractionLibrary, type FroamInteractionLibrary, type FroamInteractionRecipe } from '../project/interaction-library'
import { adoptMutationChanges, compareMutationBranches, createMutationPrototype, deterministicMutationProvider, normalizeMutationConstraints, previewMutation, type FroamMutationLevel, type FroamMutationProtection } from '../project/mutation'
import { FROAM_PHYSICS_PRESETS, interactionWithGravity, interactionWithPhysics, physicsPreset, type FroamGravityDescription, type FroamPhysicsPreset } from '../project/physics'
import { attachSoundToInteraction, importSoundAsset } from '../project/sound'
import { runSyntheticUx, syntheticRunAnalysis, type FroamSyntheticRun } from '../project/synthetic-ux'
import { createTrailerStoryboard, removeTrailerShot, reorderTrailerShot, trailerStoryboardAnalysis, type FroamTrailerStoryboard } from '../project/trailer'
import { createNativeSamplingRecorder, samplingSessionToRecipe, samplingTimeline } from '../project/ui-sampling'
import type { FroamInteraction, FroamProjectDocument } from '../project/types'

export type FroamLab = 'overview' | 'mutate' | 'interactions' | 'sample' | 'physics' | 'break' | 'user' | 'sound' | 'trailer' | 'reality'
type Props = { open: boolean; onClose: () => void; project: FroamProjectDocument; onProjectChange: Dispatch<SetStateAction<FroamProjectDocument>>; actorId: string; selectedNodeId?: string; selectedElement: HTMLElement | null; onToast: (message: string) => void; requestedLab?: FroamLab; flags?: FroamLabsFlags; onFlagsChange?: (flags: FroamLabsFlags) => void; onTemporalOwnerChange?: (owner: 'sampling' | 'trailer' | null) => void; onActivityChange?: (activity: 'mutating' | 'chaos' | 'synthetic' | null) => void }
const LAB_TAB_KEY = 'froam-labs-tab-v1'
const PROTECTIONS: FroamMutationProtection[] = ['copy', 'brand-colors', 'logo', 'product-data', 'navigation', 'component', 'section']
export default function FroamLabs(props: Props) {
  const [localFlags, setLocalFlags] = useState(() => readFroamLabsFlags(typeof localStorage === 'undefined' ? undefined : localStorage)); const flags = props.flags ?? localFlags; const [active, setActive] = useState<FroamLab>(() => { try { return (localStorage.getItem(LAB_TAB_KEY) as FroamLab | null) ?? 'overview' } catch { return 'overview' } }); const [level, setLevel] = useState<FroamMutationLevel>('safe'); const [protect, setProtect] = useState<FroamMutationProtection[]>(['copy', 'product-data']); const [mutating, setMutating] = useState(false); const [search, setSearch] = useState(''); const [sampling, setSampling] = useState(false); const [preset, setPreset] = useState<FroamPhysicsPreset>('Soft Spring'); const [gravity, setGravity] = useState<FroamGravityDescription['mode']>('attract'); const [chaos, setChaos] = useState<FroamChaosReport | null>(null); const [synthetic, setSynthetic] = useState<FroamSyntheticRun | null>(null); const [storyboard, setStoryboard] = useState<FroamTrailerStoryboard | null>(null)
  const recorder = useRef<ReturnType<typeof createNativeSamplingRecorder> | null>(null)
  const state = useMemo(() => deriveBranchState(props.project), [props.project]); const library = (props.project.metadata?.interactionLibrary ?? {}) as FroamInteractionLibrary; const mutations = (props.project.metadata?.mutations ?? []) as Array<{ id: string; sourceBranchId: string; sourceCheckpointId: string; level: FroamMutationLevel; provider: string; operationIds: string[] }>; const latest = mutations.at(-1)
  const constraints = useMemo(() => normalizeMutationConstraints(level, { protect }), [level, protect]); const proposal = useMemo(() => props.selectedNodeId ? previewMutation(deterministicMutationProvider, { state, scopeNodeIds: [props.selectedNodeId], level, constraints, seed: mutations.length, now: props.project.updatedAt }) : null, [state, props.selectedNodeId, level, constraints, mutations.length, props.project.updatedAt]); const comparison = latest && props.project.branches[latest.id] ? compareMutationBranches(props.project, latest.sourceBranchId, latest.id) : null
  useEffect(() => { if (props.requestedLab) setActive(props.requestedLab) }, [props.requestedLab])
  useEffect(() => {
    const flagByLab: Partial<Record<FroamLab, keyof FroamLabsFlags>> = { mutate: 'mutate', interactions: 'interactionLibrary', sample: 'uiSampling', physics: 'designPhysics', break: 'chaosTesting', user: 'syntheticUx', sound: 'uiSound', trailer: 'trailerGenerator', reality: 'realityMode' }
    const requiredFlag = flagByLab[active]
    if (requiredFlag && !flags[requiredFlag]) setActive('overview')
  }, [active, flags])
  useEffect(() => { try { localStorage.setItem(LAB_TAB_KEY, active) } catch { /* optional preference */ }; props.onTemporalOwnerChange?.(props.open && active === 'sample' ? 'sampling' : props.open && active === 'trailer' ? 'trailer' : null) }, [active, props.open, props.onTemporalOwnerChange])
  const updateFlag = (key: keyof FroamLabsFlags, enabled: boolean) => { const next = { ...flags, [key]: enabled }; setLocalFlags(next); writeFroamLabsFlags(typeof localStorage === 'undefined' ? undefined : localStorage, next); props.onFlagsChange?.(next) }
  const saveLibrary = (next: FroamInteractionLibrary) => props.onProjectChange((project) => ({ ...project, updatedAt: Date.now(), metadata: { ...project.metadata, interactionLibrary: next } }))
  const addEvents = (events: ReturnType<typeof createProjectEvent>[]) => props.onProjectChange((project) => appendProjectEvents(project, events))
  const eventFor = (type: Parameters<typeof createProjectEvent>[0]['type'], payload: Parameters<typeof createProjectEvent>[0]['payload'], targetIds: string[], label: string) => createProjectEvent({ projectId: props.project.id, branchId: props.project.activeBranchId, actorId: props.actorId, clock: Math.max(0, ...props.project.events.map((item) => item.clock)) + 1, type, payload, targetIds, label })
  function mutate() { if (!props.selectedNodeId) return props.onToast('Select a scanned node before mutating'); setMutating(true); props.onActivityChange?.('mutating'); const delay = matchMedia('(prefers-reduced-motion: reduce)').matches ? 0 : 420; window.setTimeout(() => { try { const id = `mutation-${String(mutations.length + 1).padStart(3, '0')}`; const result = createMutationPrototype(props.project, { branchId: id, actorId: props.actorId, level, constraints, scopeNodeIds: [props.selectedNodeId!], seed: mutations.length }); props.onProjectChange(result.project); props.onToast(`${id} created; ${result.proposals.length} branch-scoped changes`) } catch (error) { props.onToast(error instanceof Error ? error.message : 'Mutation failed') } finally { setMutating(false); props.onActivityChange?.(null) } }, delay) }
  function adopt() { if (!latest || !comparison) return; const result = adoptMutationChanges(props.project, { mutationBranchId: latest.id, targetBranchId: latest.sourceBranchId, eventIds: comparison.eventIds, actorId: props.actorId }); if (result.status === 'refused') return props.onToast(`Adoption refused: ${result.conflicts[0]?.reason}`); props.onProjectChange(result.project); props.onToast(`${result.adoptedEventIds.length} compatible changes adopted with provenance`) }
  function saveFirstInteraction() { const interaction = Object.values(state.interactions)[0]; if (!interaction) return props.onToast('Create an interaction before saving a recipe'); const recipe: FroamInteractionRecipe = { id: `recipe:${Date.now().toString(36)}`, name: interaction.name, category: 'Feedback', interaction, bindings: { source: { role: 'trigger', originalNodeId: interaction.sourceId, required: true }, targets: interaction.targetIds.map((id, index) => ({ role: index ? `target-${index + 1}` : 'target', originalNodeId: id, required: true })) }, provenance: { kind: 'native', source: 'froam', projectId: props.project.id, branchId: props.project.activeBranchId, createdAt: Date.now(), sourceInteractionId: interaction.id, originalImplementation: 'froam' } }; saveLibrary(saveInteractionRecipe(library, recipe)) }
  function applyFirstRecipe() { const recipe = searchInteractionLibrary(library, { query: search })[0]; if (!recipe || !props.selectedNodeId) return props.onToast('Select a node and recipe'); try { const targetIds = Object.fromEntries(recipe.bindings.targets.map((role) => [role.role, props.selectedNodeId!])); const interaction = applyInteractionRecipe(recipe, { sourceId: props.selectedNodeId, targetIds }); addEvents([eventFor('interaction.upserted', { interaction }, [props.selectedNodeId], `Applied ${recipe.name}`)]) } catch (error) { props.onToast(error instanceof Error ? error.message : 'Binding failed') } }
  function toggleSampling() { if (!flags.uiSampling || !props.selectedElement || !props.selectedNodeId) return props.onToast('Enable Sampling and select a Froam-controlled element'); if (!sampling) { recorder.current = createNativeSamplingRecorder({ root: document.body, targets: [{ element: props.selectedElement, role: 'target', nodeId: props.selectedNodeId }], trigger: 'click', sourceRole: 'trigger' }).start(); setSampling(true); props.onToast('Sampling observable events, mutations and computed styles') } else { const session = recorder.current?.stop(); recorder.current = null; setSampling(false); if (!session) return; const recipe = samplingSessionToRecipe(session, { recipeId: `sampled:${Date.now().toString(36)}`, name: 'Observed interaction', projectId: props.project.id, branchId: props.project.activeBranchId }); saveLibrary(saveInteractionRecipe(library, recipe)); props.onToast(`${samplingTimeline(session).length} observations saved as a sampled recipe`) } }
  function applyPhysics() { if (!props.selectedNodeId) return props.onToast('Select a node for Physics'); const base: FroamInteraction = Object.values(state.interactions)[0] ?? { id: `physics:${props.selectedNodeId}`, name: `${preset} interaction`, sourceId: props.selectedNodeId, targetIds: [props.selectedNodeId], trigger: 'drag', timeline: [{ at: 0, values: { transform: 'translate3d(0,0,0)' } }, { at: 1, values: { transform: 'translate3d(0,0,0)' } }] }; let interaction = interactionWithPhysics(base, physicsPreset(preset)); if (flags.uiGravity) interaction = interactionWithGravity(interaction, { mode: gravity, strength: 24, radius: 180, sourceId: props.selectedNodeId, labOnly: ['stay-near','avoid','group'].includes(gravity) }); addEvents([eventFor('interaction.upserted', { interaction }, [props.selectedNodeId], 'Design Physics')]); props.onToast(`${preset} compiled into deterministic runtime behavior`) }
  async function breakPage() { if (!flags.chaosTesting) return; props.onActivityChange?.('chaos'); try { let viewport = { width: window.innerWidth, height: window.innerHeight }; const report = await runChaosTesting({ scenarios: createDefaultChaosScenarios().slice(0, 4), state, adapter: { apply(event) { if (event.type === 'viewport') viewport = { width: event.width, height: event.height } }, capture() { const elements = [...document.querySelectorAll<HTMLElement>('[data-froam-id]')]; return { viewport, nodes: elements.map((element) => { const rect = element.getBoundingClientRect(); const css = getComputedStyle(element); return { nodeId: element.dataset.froamId!, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, visible: css.display !== 'none' && css.visibility !== 'hidden', clipped: element.scrollWidth > element.clientWidth + 2 || element.scrollHeight > element.clientHeight + 2, reachable: !element.matches(':disabled') } }) } }, restore() {} } }); setChaos(report); const analysis = chaosReportAnalysis(report); addEvents([eventFor('analysis.upserted', { analysis }, analysis.targetIds, 'BREAK THIS PAGE')]); props.onToast(`${report.total} realities: ${report.passed} passed, ${report.warnings} warnings, ${report.failed} failed`) } finally { props.onActivityChange?.(null) } }
  async function testUser() { const flow = Object.values(state.flows)[0]; if (!flow?.entryNodeId || flow.nodeIds.length < 2) return props.onToast('Synthetic UX needs a Product Flow with at least two nodes'); props.onActivityChange?.('synthetic'); try { const run = await runSyntheticUx({ id: `goal:${Date.now().toString(36)}`, goal: `Reach ${flow.nodeIds.at(-1)}`, startNodeId: flow.entryNodeId, successNodeIds: [flow.nodeIds.at(-1)!] }, { flow, state }); setSynthetic(run); addEvents([eventFor('analysis.upserted', { analysis: syntheticRunAnalysis(run) }, syntheticRunAnalysis(run).targetIds, 'Synthetic UX run')]); props.onToast(run.success ? `Synthetic user succeeded in ${run.steps.length} steps` : `Synthetic user failed: ${run.importantFailures[0]}`) } finally { props.onActivityChange?.(null) } }
  function importSound(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => { const id = `sound:${Date.now().toString(36)}`; const sounds = importSoundAsset(Object.fromEntries(Object.entries(state.assets).filter(([, asset]) => asset.kind === 'audio')), { id, name: file.name, url: String(reader.result), mimeType: file.type || 'audio/mpeg' }); const asset = sounds[id]; const interaction = Object.values(state.interactions)[0]; const events = [eventFor('asset.upserted', { asset }, [id], 'Imported UI sound')]; if (interaction) events.push(eventFor('interaction.upserted', { interaction: attachSoundToInteraction(interaction, { assetId: id, timing: 'start', volume: .7 }, sounds) }, interaction.targetIds, 'Attached UI sound')); addEvents(events); props.onToast(interaction ? 'Sound imported and attached to the first interaction' : 'Sound imported into the project collection') }; reader.readAsDataURL(file) }
  function persistStoryboard(value: FroamTrailerStoryboard) { setStoryboard(value); const analysis = trailerStoryboardAnalysis(value); addEvents([eventFor('analysis.upserted', { analysis }, analysis.targetIds, 'Edited trailer storyboard')]) }
  function createTrailer(durationSeconds: 10 | 15 | 30) { if (!flags.trailerGenerator) return; const value = createTrailerStoryboard({ state, branchId: props.project.activeBranchId, durationSeconds, mutationBranchId: latest?.id }); persistStoryboard(value); props.onToast(`${value.shots.length} real product-state shots created`) }
  if (!props.open) return null
  const labs: Array<[FroamLab, string]> = [
    ['overview', 'Laboratory'],
    ...(flags.mutate ? [['mutate', '☣ MUTATE'] as [FroamLab, string]] : []),
    ...(flags.interactionLibrary ? [['interactions', 'Interactions'] as [FroamLab, string]] : []),
    ...(flags.uiSampling ? [['sample', '◉ SAMPLE'] as [FroamLab, string]] : []),
    ...(flags.designPhysics ? [['physics', 'Physics'] as [FroamLab, string]] : []),
    ...(flags.chaosTesting ? [['break', 'BREAK'] as [FroamLab, string]] : []),
    ...(flags.syntheticUx ? [['user', 'Test User'] as [FroamLab, string]] : []),
    ...(flags.uiSound ? [['sound', 'Sound'] as [FroamLab, string]] : []),
    ...(flags.trailerGenerator ? [['trailer', 'Trailer'] as [FroamLab, string]] : []),
    ...(flags.realityMode ? [['reality', 'Reality'] as [FroamLab, string]] : []),
  ]
  return <aside className={`froam-labs ${mutating ? 'is-mutating' : ''}`} data-chef-editor-root="true"><header><div><Beaker size={16}/><strong>Interface Laboratory</strong><small>Froam v8 · Experiments</small></div><button type="button" aria-label="Close Interface Laboratory" onClick={props.onClose}><X size={15}/></button></header><nav>{labs.map(([id,label]) => <button key={id} className={active === id ? 'is-active' : ''} onClick={() => setActive(id)}>{label}</button>)}</nav><main>
    {active === 'overview' && <section className="froam-labs__flags"><h3>Experiment controls</h3><p>Enable only the experimental tools you want in this workspace. Enabled tools appear in the Experiment rail.</p>{(Object.keys(flags) as Array<keyof FroamLabsFlags>).map((key) => <Flag key={key} flag={key} value={flags[key]} update={updateFlag}/>)}</section>}
    {active === 'mutate' && <section className="froam-labs__mutate"><h3>☣ MUTATE</h3><p>Fork first. The source branch is immutable.</p><select value={level} onChange={(event) => setLevel(event.target.value as FroamMutationLevel)}><option value="safe">SAFE</option><option value="experimental">EXPERIMENTAL</option><option value="unhinged">UNHINGED</option></select><div className="froam-labs__chips">{PROTECTIONS.map((item) => <label key={item}><input type="checkbox" checked={protect.includes(item)} onChange={() => setProtect((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current,item])}/>{item}</label>)}</div><div className="froam-labs__proposal">{proposal?.summary.map((item,index) => <p key={index}><b>{item.domain}</b>{item.rationale}<small>{Math.round(item.confidence*100)}% · {item.targets} target</small></p>)}</div><button disabled={!flags.mutate || mutating} onClick={mutate}>{mutating ? 'Froam Mutagen active…' : proposal?.requiresConfirmation ? 'MUTATE NOW' : 'Create mutation'}</button>{comparison && <div className="froam-labs__compare"><span>Original<br/><b>{comparison.sourceBranchId}</b></span><i>VS</i><span>Mutation<br/><b>{comparison.mutationBranchId}</b></span><small>{comparison.structural} structural · {comparison.visual} visual · {comparison.interactions} interaction</small><button onClick={adopt}>Adopt compatible changes</button></div>}</section>}
    {active === 'interactions' && <section><h3><BookOpen size={14}/> Interaction Library</h3><input placeholder="Search behavior" value={search} onChange={(event) => setSearch(event.target.value)}/><div className="froam-labs__actions"><button disabled={!flags.interactionLibrary} onClick={saveFirstInteraction}>Save existing</button><button disabled={!flags.interactionLibrary} onClick={applyFirstRecipe}>Apply first result</button></div><ul>{searchInteractionLibrary(library,{query:search}).map((recipe) => <li key={recipe.id}><b>{recipe.name}</b><small>{recipe.category ?? 'Uncategorized'} · {recipe.provenance.kind} · {previewInteractionRecipe(recipe,{samples:4}).length} preview frames</small><button disabled={!flags.interactionLibrary} onClick={() => saveLibrary(deleteInteractionRecipe(library, recipe.id))}>Remove</button></li>)}</ul></section>}
    {active === 'sample' && <section><h3><Radio size={14}/> Native Sampling</h3><p>Captures observable events, mutations, styles, layout and timing—not source implementation.</p><button disabled={!flags.uiSampling} className={sampling ? 'is-danger' : ''} onClick={toggleSampling}>{sampling ? 'Stop and reconstruct recipe' : '● Record selected region'}</button><Flag flag="externalSampling" value={flags.externalSampling} update={updateFlag}/><small>External prototype is separately permissioned under experiments/external-sampler.</small></section>}
    {active === 'physics' && <section><h3><Atom size={14}/> Design Physics</h3><select value={preset} onChange={(event) => setPreset(event.target.value as FroamPhysicsPreset)}>{Object.keys(FROAM_PHYSICS_PRESETS).map((name) => <option key={name}>{name}</option>)}</select><select value={gravity} onChange={(event) => setGravity(event.target.value as FroamGravityDescription['mode'])}>{['attract','repel','follow','anchor','stay-near','avoid','group'].map((mode) => <option key={mode}>{mode}</option>)}</select><Flag flag="uiGravity" value={flags.uiGravity} update={updateFlag}/><button disabled={!flags.designPhysics} onClick={applyPhysics}>Compile Physics interaction</button></section>}
    {active === 'break' && <section><h3><FlaskConical size={14}/> BREAK THIS PAGE</h3><p>Run isolated viewport realities here. Content, assets, locale, network, API, permissions and sessions use the same adapter boundary when a host can safely simulate them.</p><button disabled={!flags.chaosTesting} onClick={() => void breakPage()}>Run tested viewport realities</button>{chaos && <div className="froam-labs__score"><b>{chaos.total} scenarios</b><span>{chaos.passed} passed · {chaos.warnings} warnings · {chaos.failed} failed</span>{chaos.scenarios.flatMap((item) => item.failures).slice(0,6).map((failure) => <small key={failure.id}>{failure.severity}: {failure.message}</small>)}</div>}</section>}
    {active === 'user' && <section><h3><Activity size={14}/> Synthetic UX</h3><p>Deterministic Product Flow task runner. Not a substitute for human usability testing.</p><button disabled={!flags.syntheticUx} onClick={() => void testUser()}>Run first flow goal</button>{synthetic && <div className="froam-labs__score"><b>{synthetic.success ? 'Goal completed' : 'Goal failed'}</b><span>{synthetic.steps.length} steps · {synthetic.clicks} clicks · {synthetic.deadEnds} dead ends</span></div>}</section>}
    {active === 'sound' && <section><h3><Volume2 size={14}/> UI Sound</h3><p>Project-local optional audio synchronized through FroamInteraction. Browser autoplay rules apply.</p><label className="froam-labs__upload">Import sound<input type="file" accept="audio/*" disabled={!flags.uiSound} onChange={(event) => importSound(event.target.files?.[0])}/></label><span>{Object.values(state.assets).filter((asset) => asset.kind === 'audio').length} project sounds</span></section>}
    {active === 'trailer' && <section><h3>Trailer Generator</h3><p>Editable storyboard from real Product Flow nodes, interactions and mutation branches.</p><div className="froam-labs__actions">{([10,15,30] as const).map((duration) => <button key={duration} disabled={!flags.trailerGenerator} onClick={() => createTrailer(duration)}>{duration}s</button>)}</div>{storyboard && <ol>{storyboard.shots.map((shot, index) => <li key={shot.id}><b>{(shot.startMs/1000).toFixed(1)}s</b> {shot.label}<span className="froam-labs__actions"><button disabled={index === 0} onClick={() => persistStoryboard(reorderTrailerShot(storyboard, shot.id, index - 1))}>↑</button><button disabled={index === storyboard.shots.length - 1} onClick={() => persistStoryboard(reorderTrailerShot(storyboard, shot.id, index + 1))}>↓</button><button disabled={storyboard.shots.length === 1} onClick={() => persistStoryboard(removeTrailerShot(storyboard, shot.id))}>Remove</button></span></li>)}</ol>}</section>}
    {active === 'reality' && <section><h3>Reality <small>Research</small></h3><p>Bounded probable-screen detection and quadrilateral rectification are available through the project API. Manual confirmation is mandatory; Froam does not claim camera calibration or scene understanding.</p><button type="button" disabled={!flags.realityMode} onClick={() => props.onToast('Reality remains a bounded research boundary; import/camera UX is intentionally deferred until evaluated')}>Review research boundary</button></section>}
  </main></aside>
}
function Flag(props: { flag: keyof FroamLabsFlags; value: boolean; update: (key: keyof FroamLabsFlags, enabled: boolean) => void }) { return <label className="froam-labs__flag"><input type="checkbox" checked={props.value} onChange={(event) => props.update(props.flag,event.target.checked)}/><span>{props.flag.replace(/[A-Z]/g,(letter)=>` ${letter}`).trim()}</span><em>Experimental</em></label> }
