import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from 'react'
import { Activity, Atom, Beaker, BookOpen, Eye, FlaskConical, Radio, Sparkles, Volume2, X } from 'lucide-react'
import { appendProjectEvents, createProjectEvent, deriveBranchState } from '../project/event-log'
import { chaosReportAnalysis, createDefaultChaosScenarios, runChaosTesting, type FroamChaosReport } from '../project/chaos'
import { readFroamLabsFlags, writeFroamLabsFlags, type FroamLabsFlags } from '../project/experiments'
import { applyInteractionRecipe, deleteInteractionRecipe, previewInteractionRecipe, saveInteractionRecipe, searchInteractionLibrary, type FroamInteractionLibrary, type FroamInteractionRecipe } from '../project/interaction-library'
import { adoptMutationChanges, compareMutationBranches, createMutationPrototype, deterministicMutationProvider, normalizeMutationConstraints, previewMutation, type FroamMutationLevel, type FroamMutationProtection } from '../project/mutation'
import { FROAM_PHYSICS_PRESETS, gravityForce, interactionWithGravity, interactionWithPhysics, physicsPreset, type FroamGravityDescription, type FroamPhysicsPreset } from '../project/physics'
import { createNativeSamplingRecorder, samplingSessionToRecipe, samplingTimeline } from '../project/ui-sampling'
import type { FroamInteraction, FroamProjectDocument } from '../project/types'
import { animationPresetInteraction, FROAM_ANIMATION_PRESETS, type FroamAnimationPreset } from './FroamAnimationPresets'
import { createArchiveItem, minimalArchiveDna } from '../project/archive'

export type FroamLab = 'overview' | 'mutate' | 'interactions' | 'sample' | 'physics' | 'break' | 'user' | 'sound' | 'trailer' | 'reality'
type Props = { open: boolean; onClose: () => void; project: FroamProjectDocument; onProjectChange: Dispatch<SetStateAction<FroamProjectDocument>>; actorId: string; selectedNodeId?: string; selectedElement: HTMLElement | null; onToast: (message: string) => void; requestedLab?: FroamLab; flags?: FroamLabsFlags; onFlagsChange?: (flags: FroamLabsFlags) => void; onTemporalOwnerChange?: (owner: 'sampling' | 'trailer' | null) => void; onActivityChange?: (activity: 'mutating' | 'chaos' | 'synthetic' | null) => void }
const LAB_TAB_KEY = 'froam-labs-tab-v1'
const PROTECTIONS: FroamMutationProtection[] = ['copy', 'brand-colors', 'logo', 'product-data', 'navigation', 'component', 'section']
export default function FroamLabs(props: Props) {
  const [localFlags, setLocalFlags] = useState(() => readFroamLabsFlags(typeof localStorage === 'undefined' ? undefined : localStorage)); const flags = props.flags ?? localFlags; const [active, setActive] = useState<FroamLab>(() => { try { return (localStorage.getItem(LAB_TAB_KEY) as FroamLab | null) ?? 'overview' } catch { return 'overview' } }); const [level, setLevel] = useState<FroamMutationLevel>('safe'); const [protect, setProtect] = useState<FroamMutationProtection[]>(['copy', 'product-data']); const [mutating, setMutating] = useState(false); const [search, setSearch] = useState(''); const [sampling, setSampling] = useState(false); const [preset, setPreset] = useState<FroamPhysicsPreset>('Soft Spring'); const [gravity, setGravity] = useState<FroamGravityDescription['mode']>('attract'); const [gravityStrength, setGravityStrength] = useState(24); const [gravityRadius, setGravityRadius] = useState(180); const [chaos, setChaos] = useState<FroamChaosReport | null>(null); const [lastLabInteraction, setLastLabInteraction] = useState<FroamInteraction | null>(null)
  const recorder = useRef<ReturnType<typeof createNativeSamplingRecorder> | null>(null)
  const state = useMemo(() => deriveBranchState(props.project), [props.project]); const library = (props.project.metadata?.interactionLibrary ?? {}) as FroamInteractionLibrary; const mutations = (props.project.metadata?.mutations ?? []) as Array<{ id: string; sourceBranchId: string; sourceCheckpointId: string; level: FroamMutationLevel; provider: string; operationIds: string[] }>; const latest = mutations.at(-1)
  const constraints = useMemo(() => normalizeMutationConstraints(level, { protect }), [level, protect]); const proposal = useMemo(() => props.selectedNodeId ? previewMutation(deterministicMutationProvider, { state, scopeNodeIds: [props.selectedNodeId], level, constraints, seed: mutations.length, now: props.project.updatedAt }) : null, [state, props.selectedNodeId, level, constraints, mutations.length, props.project.updatedAt]); const comparison = latest && props.project.branches[latest.id] ? compareMutationBranches(props.project, latest.sourceBranchId, latest.id) : null
  useEffect(() => { if (props.requestedLab) setActive(props.requestedLab) }, [props.requestedLab])
  useEffect(() => {
    const flagByLab: Partial<Record<FroamLab, keyof FroamLabsFlags>> = { mutate: 'mutate', interactions: 'interactionLibrary', sample: 'uiSampling', physics: 'designPhysics', break: 'chaosTesting', user: 'syntheticUx', sound: 'uiSound', trailer: 'trailerGenerator', reality: 'realityMode' }
    const requiredFlag = flagByLab[active]
    if (requiredFlag && !flags[requiredFlag]) setActive('overview')
  }, [active, flags])
  useEffect(() => { try { localStorage.setItem(LAB_TAB_KEY, active) } catch { /* optional preference */ }; props.onTemporalOwnerChange?.(props.open && active === 'sample' ? 'sampling' : props.open && active === 'trailer' ? 'trailer' : null) }, [active, props.open, props.onTemporalOwnerChange])
  const updateFlag = (key: keyof FroamLabsFlags, enabled: boolean) => { const next = { ...flags, [key]: enabled }; setLocalFlags(next); writeFroamLabsFlags(typeof localStorage === 'undefined' ? undefined : localStorage, next); props.onFlagsChange?.(next) }
  const saveLibrary = (next: FroamInteractionLibrary) => props.onProjectChange((project) => ({ ...project, updatedAt: Date.now(), metadata: { ...project.metadata, interactionLibrary: next } }))
  const addEvents = (events: ReturnType<typeof createProjectEvent>[]) => props.onProjectChange((project) => appendProjectEvents(project, events))
  const eventFor = (type: Parameters<typeof createProjectEvent>[0]['type'], payload: Parameters<typeof createProjectEvent>[0]['payload'], targetIds: string[], label: string) => createProjectEvent({ projectId: props.project.id, branchId: props.project.activeBranchId, actorId: props.actorId, clock: Math.max(0, ...props.project.events.map((item) => item.clock)) + 1, type, payload, targetIds, label })
  function mutate() { if (!props.selectedNodeId) return props.onToast('Select a scanned node before mutating'); setMutating(true); props.onActivityChange?.('mutating'); const delay = matchMedia('(prefers-reduced-motion: reduce)').matches ? 0 : 420; window.setTimeout(() => { try { const id = `mutation-${String(mutations.length + 1).padStart(3, '0')}`; const result = createMutationPrototype(props.project, { branchId: id, actorId: props.actorId, level, constraints, scopeNodeIds: [props.selectedNodeId!], seed: mutations.length }); props.onProjectChange(result.project); props.onToast(`${id} created; ${result.proposals.length} branch-scoped changes`) } catch (error) { props.onToast(error instanceof Error ? error.message : 'Mutation failed') } finally { setMutating(false); props.onActivityChange?.(null) } }, delay) }
  function adopt() { if (!latest || !comparison) return; const result = adoptMutationChanges(props.project, { mutationBranchId: latest.id, targetBranchId: latest.sourceBranchId, eventIds: comparison.eventIds, actorId: props.actorId }); if (result.status === 'refused') return props.onToast(`Adoption refused: ${result.conflicts[0]?.reason}`); props.onProjectChange(result.project); props.onToast(`${result.adoptedEventIds.length} compatible changes adopted with provenance`) }
  function saveFirstInteraction() { const interaction = Object.values(state.interactions)[0]; if (!interaction) return props.onToast('Create an interaction before saving a recipe'); const recipe: FroamInteractionRecipe = { id: `recipe:${Date.now().toString(36)}`, name: interaction.name, category: 'Feedback', interaction, bindings: { source: { role: 'trigger', originalNodeId: interaction.sourceId, required: true }, targets: interaction.targetIds.map((id, index) => ({ role: index ? `target-${index + 1}` : 'target', originalNodeId: id, required: true })) }, provenance: { kind: 'native', source: 'froam', projectId: props.project.id, branchId: props.project.activeBranchId, createdAt: Date.now(), sourceInteractionId: interaction.id, originalImplementation: 'froam' } }; saveLibrary(saveInteractionRecipe(library, recipe)) }
  function applyFirstRecipe() { const recipe = searchInteractionLibrary(library, { query: search })[0]; if (!recipe || !props.selectedNodeId) return props.onToast('Select a node and recipe'); try { const targetIds = Object.fromEntries(recipe.bindings.targets.map((role) => [role.role, props.selectedNodeId!])); const interaction = applyInteractionRecipe(recipe, { sourceId: props.selectedNodeId, targetIds }); addEvents([eventFor('interaction.upserted', { interaction }, [props.selectedNodeId], `Applied ${recipe.name}`)]) } catch (error) { props.onToast(error instanceof Error ? error.message : 'Binding failed') } }
  function previewMotionPreset(motion: FroamAnimationPreset) { if (!props.selectedElement) return props.onToast('Select an element to preview motion'); const config = motion.config; const keyframes = (config.keyframes ?? []).map((keyframe) => ({ ...keyframe.properties, offset: keyframe.offset / 100 })); if (!keyframes.length) return; props.selectedElement.animate(keyframes, { duration: matchMedia('(prefers-reduced-motion: reduce)').matches ? 1 : config.duration ?? 600, delay: config.delay, easing: config.easing, iterations: config.iterations === 0 ? 2 : Math.min(config.iterations ?? 1, 2), direction: config.direction, fill: config.fillMode ?? 'both' }) }
  function applyMotionPreset(motion: FroamAnimationPreset) { if (!props.selectedNodeId) return props.onToast('Select a scanned node before applying behavior'); const interaction = animationPresetInteraction(motion, props.selectedNodeId); addEvents([eventFor('interaction.upserted', { interaction }, [props.selectedNodeId], `Applied ${motion.label}`)]); setLastLabInteraction(interaction); previewMotionPreset(motion); props.onToast(`${motion.label} added as a ${interaction.trigger} interaction`) }
  function toggleSampling() { if (!flags.uiSampling || !props.selectedElement || !props.selectedNodeId) return props.onToast('Enable Sampling and select a Froam-controlled element'); if (!sampling) { recorder.current = createNativeSamplingRecorder({ root: document.body, targets: [{ element: props.selectedElement, role: 'target', nodeId: props.selectedNodeId }], trigger: 'click', sourceRole: 'trigger' }).start(); setSampling(true); props.onToast('Sampling observable events, mutations and computed styles') } else { const session = recorder.current?.stop(); recorder.current = null; setSampling(false); if (!session) return; const recipe = samplingSessionToRecipe(session, { recipeId: `sampled:${Date.now().toString(36)}`, name: 'Observed interaction', projectId: props.project.id, branchId: props.project.activeBranchId }); saveLibrary(saveInteractionRecipe(library, recipe)); props.onToast(`${samplingTimeline(session).length} observations saved as a sampled recipe`) } }
  function previewGravity() { if (!props.selectedElement) return props.onToast('Select an element to preview gravity'); const vector = gravityForce({ mode: gravity, strength: gravityStrength, radius: gravityRadius }, { x: 0, y: 0 }, { x: Math.min(96, gravityRadius * .5), y: -28 }); const x = Math.round(vector.x * 2.2); const y = Math.round(vector.y * 2.2); props.selectedElement.animate([{ transform: 'translate3d(0,0,0)' }, { transform: `translate3d(${x}px,${y}px,0)`, offset: .55 }, { transform: 'translate3d(0,0,0)' }], { duration: matchMedia('(prefers-reduced-motion: reduce)').matches ? 1 : 760, easing: 'cubic-bezier(.22,1,.36,1)' }); props.onToast(`${gravity} force preview: ${x >= 0 ? 'right' : 'left'} ${Math.abs(x)}px, ${y >= 0 ? 'down' : 'up'} ${Math.abs(y)}px`) }
  function applyPhysics() { if (!props.selectedNodeId) return props.onToast('Select a node for Physics'); const base: FroamInteraction = Object.values(state.interactions)[0] ?? { id: `physics:${props.selectedNodeId}`, name: `${preset} interaction`, sourceId: props.selectedNodeId, targetIds: [props.selectedNodeId], trigger: 'drag', timeline: [{ at: 0, values: { transform: 'translate3d(0,0,0)' } }, { at: 1, values: { transform: 'translate3d(0,0,0)' } }] }; let interaction = interactionWithPhysics(base, physicsPreset(preset)); if (flags.uiGravity) interaction = interactionWithGravity(interaction, { mode: gravity, strength: gravityStrength, radius: gravityRadius, sourceId: props.selectedNodeId, labOnly: ['stay-near','avoid','group'].includes(gravity) }); addEvents([eventFor('interaction.upserted', { interaction }, [props.selectedNodeId], 'Design Physics')]); setLastLabInteraction(interaction); previewGravity(); props.onToast(`${preset} + ${gravity} compiled into deterministic runtime behavior`) }
  function saveLabArtifact() { const interaction = lastLabInteraction ?? Object.values(state.interactions).at(-1); if (!props.selectedNodeId || !interaction) return props.onToast('Apply or compile a Laboratory behavior before archiving it'); const dna = state.dna[props.selectedNodeId] ?? minimalArchiveDna(props.selectedNodeId, { role: props.selectedElement?.getAttribute('role') ?? props.selectedElement?.tagName.toLowerCase(), tagName: props.selectedElement?.tagName.toLowerCase(), motion: interaction }); const kind = interaction.physics ? 'interaction' as const : 'motion' as const; const item = createArchiveItem({ id: `archive:${kind}:${Date.now().toString(36)}`, nodeId: props.selectedNodeId, name: interaction.name, actorId: props.actorId, projectId: props.project.id, branchId: props.project.activeBranchId, dna, kind, interaction, interactionIds: [interaction.id], includes: interaction.physics ? ['motion','behavior'] : ['motion'], description: interaction.physics ? 'Laboratory behavior with deterministic physics settings.' : 'Portable motion created in Interface Laboratory.' }); addEvents([eventFor('archive.upserted', { archiveItem: item }, [props.selectedNodeId], `Archived Laboratory ${kind}`)]); props.onToast(`${interaction.name} saved to Archive`) }
  async function breakPage() { if (!flags.chaosTesting) return; props.onActivityChange?.('chaos'); try { let viewport = { width: window.innerWidth, height: window.innerHeight }; const report = await runChaosTesting({ scenarios: createDefaultChaosScenarios().slice(0, 4), state, adapter: { apply(event) { if (event.type === 'viewport') viewport = { width: event.width, height: event.height } }, capture() { const elements = [...document.querySelectorAll<HTMLElement>('[data-froam-id]')]; return { viewport, nodes: elements.map((element) => { const rect = element.getBoundingClientRect(); const css = getComputedStyle(element); return { nodeId: element.dataset.froamId!, rect: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, visible: css.display !== 'none' && css.visibility !== 'hidden', clipped: element.scrollWidth > element.clientWidth + 2 || element.scrollHeight > element.clientHeight + 2, reachable: !element.matches(':disabled') } }) } }, restore() {} } }); setChaos(report); const analysis = chaosReportAnalysis(report); addEvents([eventFor('analysis.upserted', { analysis }, analysis.targetIds, 'BREAK THIS PAGE')]); props.onToast(`${report.total} realities: ${report.passed} passed, ${report.warnings} warnings, ${report.failed} failed`) } finally { props.onActivityChange?.(null) } }
  if (!props.open) return null
  const labs: Array<[FroamLab, string]> = [
    ['overview', 'Overview'],
    ...(flags.mutate ? [['mutate', 'Variations'] as [FroamLab, string]] : []),
    ...(flags.interactionLibrary ? [['interactions', 'Interactions'] as [FroamLab, string]] : []),
    ...(flags.uiSampling ? [['sample', 'Record'] as [FroamLab, string]] : []),
    ...(flags.designPhysics ? [['physics', 'Physics'] as [FroamLab, string]] : []),
    ...(flags.chaosTesting ? [['break', 'Stress test'] as [FroamLab, string]] : []),
  ]
  if (!labs.some(([id]) => id === active)) queueMicrotask(() => setActive('overview'))
  const quickMotions = FROAM_ANIMATION_PRESETS.filter((motion) => !search.trim() || `${motion.label} ${motion.category} ${motion.description}`.toLowerCase().includes(search.toLowerCase())).slice(0, 12)
  const forceVector = gravityForce({ mode: gravity, strength: gravityStrength, radius: gravityRadius }, { x: 0, y: 0 }, { x: Math.min(96, gravityRadius * .5), y: -28 })
  const gravityCopy: Record<FroamGravityDescription['mode'], string> = { attract: 'Pulls the selected object toward its target.', repel: 'Pushes it away from its target.', follow: 'Tracks a target with a steady pull.', anchor: 'Returns the object to a fixed point.', 'stay-near': 'Keeps related objects within a chosen radius.', avoid: 'Prevents nearby objects from crowding.', group: 'Gathers related objects into a soft cluster.' }
  return <aside className={`froam-labs ${mutating ? 'is-mutating' : ''}`} data-chef-editor-root="true"><header><div><Beaker size={16}/><span><strong>Experiments</strong><small>Tools that are still being shaped</small></span></div><button type="button" aria-label="Close Experiments" onClick={props.onClose}><X size={16}/></button></header><nav>{labs.map(([id,label]) => <button key={id} className={active === id ? 'is-active' : ''} onClick={() => setActive(id)}>{label}</button>)}</nav><main>
    {active === 'overview' && <section className="froam-labs__flags"><h3>Experiments</h3><p>Try tools that are still being shaped. Turn on only the ones you want — they appear as tabs here.</p>{OFFERED_FLAGS.map((key) => <Flag key={key} flag={key} value={flags[key]} update={updateFlag}/>)}</section>}
    {active === 'mutate' && <section className="froam-labs__mutate"><h3>Variations</h3><p>Froam makes a copy of your page as a prototype, then tries changes there. Your page is never touched.</p><select value={level} onChange={(event) => setLevel(event.target.value as FroamMutationLevel)} aria-label="How far to go"><option value="safe">Subtle</option><option value="experimental">Bold</option><option value="unhinged">Wild</option></select><div className="froam-labs__chips">{PROTECTIONS.map((item) => <label key={item}><input type="checkbox" checked={protect.includes(item)} onChange={() => setProtect((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current,item])}/>{item}</label>)}</div><div className="froam-labs__proposal">{proposal?.summary.map((item,index) => <p key={index}><b>{item.domain}</b>{item.rationale}<small>{Math.round(item.confidence*100)}% · {item.targets} target</small></p>)}</div><button disabled={!flags.mutate || mutating} onClick={mutate}>{mutating ? 'Froam Mutagen active…' : proposal?.requiresConfirmation ? 'MUTATE NOW' : 'Create mutation'}</button>{comparison && <div className="froam-labs__compare"><span>Original<br/><b>{comparison.sourceBranchId}</b></span><i>VS</i><span>Mutation<br/><b>{comparison.mutationBranchId}</b></span><small>{comparison.structural} structural · {comparison.visual} visual · {comparison.interactions} interaction</small><button onClick={adopt}>Adopt compatible changes</button></div>}</section>}
    {active === 'interactions' && <section><h3><BookOpen size={14}/> Interactions</h3><p>Quick behaviors for the selected element. For exact timing, use Animate — both save to the same place.</p><p>{Object.keys(state.interactions).length} interactions are active in this branch.</p><input placeholder="Search behavior or motion" value={search} onChange={(event) => setSearch(event.target.value)}/><h4><Sparkles size={13}/> Quick behaviors</h4><div className="froam-labs__motion-grid">{quickMotions.map((motion) => <article key={motion.id}><button type="button" className="froam-labs__motion-main" disabled={!flags.interactionLibrary} onClick={() => applyMotionPreset(motion)}><b>{motion.label}</b><small>{motion.category} · {motion.config.trigger ?? 'load'}</small><span>{motion.description}</span></button><button type="button" title={`Preview ${motion.label}`} aria-label={`Preview ${motion.label}`} onClick={() => previewMotionPreset(motion)}><Eye size={13}/></button></article>)}</div><div className="froam-labs__actions"><button className="is-primary" disabled={!lastLabInteraction && !Object.keys(state.interactions).length} onClick={saveLabArtifact}>Save latest to Archive</button><button disabled={!flags.interactionLibrary} onClick={saveFirstInteraction}>Save as recipe</button><button disabled={!flags.interactionLibrary} onClick={applyFirstRecipe}>Apply saved recipe</button></div><ul>{searchInteractionLibrary(library,{query:search}).map((recipe) => <li key={recipe.id}><b>{recipe.name}</b><small>{recipe.category ?? 'Uncategorized'} · {recipe.provenance.kind} · {previewInteractionRecipe(recipe,{samples:4}).length} preview frames</small><button disabled={!flags.interactionLibrary} onClick={() => saveLibrary(deleteInteractionRecipe(library, recipe.id))}>Remove</button></li>)}</ul></section>}
    {active === 'sample' && <section><h3><Radio size={14}/> Record an interaction</h3><p>Records what you do to the selected element — clicks, changes, styles and timing — and turns it into a reusable interaction.</p><button disabled={!flags.uiSampling} className={sampling ? 'is-danger' : ''} onClick={toggleSampling}>{sampling ? 'Stop and make the interaction' : 'Record the selected element'}</button></section>}
    {active === 'physics' && <section><h3><Atom size={14}/> Physics</h3><p>Give an element weight and spring. Preview it, make it an interaction, and keep it in your archive.</p><label className="froam-labs__field"><span>Feel</span><select value={preset} onChange={(event) => setPreset(event.target.value as FroamPhysicsPreset)}>{Object.keys(FROAM_PHYSICS_PRESETS).map((name) => <option key={name}>{name}</option>)}</select></label><div className="froam-labs__gravity-modes">{(['attract','repel','follow','anchor','stay-near','avoid','group'] as const).map((mode) => <button type="button" key={mode} className={gravity === mode ? 'is-active' : ''} onClick={() => setGravity(mode)}>{mode}</button>)}</div><p className="froam-labs__explain">{gravityCopy[gravity]}</p><div className="froam-labs__force-preview" data-mode={gravity}><i className="is-source">YOU</i><span style={{ '--force-x': `${Math.round(forceVector.x * 2)}px`, '--force-y': `${Math.round(forceVector.y * 2)}px` } as React.CSSProperties}/><i className="is-target">TARGET</i><small>{gravityStrength} force · {gravityRadius}px field</small></div><label className="froam-labs__range"><span>Force <b>{gravityStrength}</b></span><input type="range" min="4" max="60" value={gravityStrength} onChange={(event) => setGravityStrength(Number(event.target.value))}/></label><label className="froam-labs__range"><span>Field radius <b>{gravityRadius}px</b></span><input type="range" min="80" max="420" step="10" value={gravityRadius} onChange={(event) => setGravityRadius(Number(event.target.value))}/></label><Flag flag="uiGravity" value={flags.uiGravity} update={updateFlag}/><div className="froam-labs__actions"><button type="button" onClick={previewGravity}><Eye size={13}/> Preview force</button><button disabled={!flags.designPhysics} onClick={applyPhysics}>Compile interaction</button><button className="is-primary" disabled={!lastLabInteraction?.physics} onClick={saveLabArtifact}>Save physics to Archive</button></div></section>}
    {active === 'break' && <section><h3><FlaskConical size={14}/> Stress test this page</h3><p>Tries the page at screen sizes and conditions it wasn't designed for, and lists what breaks.</p><button disabled={!flags.chaosTesting} onClick={() => void breakPage()}>Run the stress test</button>{chaos && <div className="froam-labs__score"><b>{chaos.total} scenarios</b><span>{chaos.passed} passed · {chaos.warnings} warnings · {chaos.failed} failed</span>{chaos.scenarios.flatMap((item) => item.failures).slice(0,6).map((failure) => <small key={failure.id}>{failure.severity}: {failure.message}</small>)}</div>}</section>}
  </main></aside>
}
const OFFERED_FLAGS: Array<keyof FroamLabsFlags> = ['mutate', 'interactionLibrary', 'uiSampling', 'designPhysics', 'uiGravity', 'chaosTesting']
const FLAG_NAMES: Record<keyof FroamLabsFlags, [string, string]> = {
  mutate: ['Variations', 'Try changes on a copy of the page'],
  interactionLibrary: ['Interactions', 'Quick behaviors for any element'],
  uiSampling: ['Record', 'Turn what you do into an interaction'],
  externalSampling: ['Record other sites', 'Sampling outside this page, with permission'],
  designPhysics: ['Physics', 'Weight and spring for elements'],
  uiGravity: ['Gravity', 'Elements that attract or repel'],
  chaosTesting: ['Stress test', 'See what breaks at odd sizes'],
  syntheticUx: ['Test a flow', 'Walk a product flow like a visitor'],
  uiSound: ['Sounds', 'Short sounds on interactions'],
  trailerGenerator: ['Trailer', 'A storyboard for a product video'],
  realityMode: ['Reality', 'Early research, screens in photos'],
}
function Flag(props: { flag: keyof FroamLabsFlags; value: boolean; update: (key: keyof FroamLabsFlags, enabled: boolean) => void }) { const [name, hint] = FLAG_NAMES[props.flag] ?? [props.flag, '']; return <label className="froam-labs__flag"><span><b>{name}</b><small>{hint}</small></span><input type="checkbox" role="switch" checked={props.value} onChange={(event) => props.update(props.flag,event.target.checked)}/></label> }
