import { useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { Atom, Beaker, BookOpen, Radio, X } from 'lucide-react'
import { appendProjectEvents, createProjectEvent, deriveBranchState } from '../project/event-log'
import { defaultFroamLabsFlags, type FroamLabsFlags } from '../project/experiments'
import { saveInteractionRecipe, type FroamInteractionLibrary, type FroamInteractionRecipe } from '../project/interaction-library'
import { createMutationPrototype, type FroamMutationLevel } from '../project/mutation'
import { interactionWithPhysics } from '../project/physics'
import { createSamplingSession, recordSamplingFrame, samplingSessionToRecipe } from '../project/ui-sampling'
import type { FroamInteraction, FroamProjectDocument } from '../project/types'

type Props = { open: boolean; onClose: () => void; project: FroamProjectDocument; onProjectChange: Dispatch<SetStateAction<FroamProjectDocument>>; actorId: string; selectedNodeId?: string; selectedElement: HTMLElement | null; onToast: (message: string) => void }
const FLAGS_KEY = 'froam-labs-flags-v1'
function loadFlags() { try { return { ...defaultFroamLabsFlags(), ...JSON.parse(localStorage.getItem(FLAGS_KEY) ?? '{}') } as FroamLabsFlags } catch { return defaultFroamLabsFlags() } }
function styles(element: HTMLElement) { const value = getComputedStyle(element); return { opacity: value.opacity, transform: value.transform, width: value.width, height: value.height, visibility: value.visibility } }
export default function FroamLabs(props: Props) {
  const [flags, setFlags] = useState(loadFlags); const [level, setLevel] = useState<FroamMutationLevel>('safe'); const [mutating, setMutating] = useState(false); const [spring, setSpring] = useState({ stiffness: 170, damping: 26, mass: 1 })
  const state = useMemo(() => deriveBranchState(props.project), [props.project]); const library = (props.project.metadata?.interactionLibrary ?? {}) as FroamInteractionLibrary; const mutations = (props.project.metadata?.mutations ?? []) as Array<{ id: string; sourceBranchId: string; level: string; provider: string }>
  const updateFlag = (key: keyof FroamLabsFlags, enabled: boolean) => { const next = { ...flags, [key]: enabled }; setFlags(next); try { localStorage.setItem(FLAGS_KEY, JSON.stringify(next)) } catch { /* optional preference */ } }
  const saveLibrary = (next: FroamInteractionLibrary) => props.onProjectChange((project) => ({ ...project, updatedAt: Date.now(), metadata: { ...project.metadata, interactionLibrary: next } }))
  function mutate() { if (!props.selectedNodeId) return props.onToast('Select a scanned node before mutating'); setMutating(true); window.setTimeout(() => { try { const id = `mutation-${String(mutations.length + 1).padStart(3, '0')}`; const result = createMutationPrototype(props.project, { branchId: id, actorId: props.actorId, level, scopeNodeIds: [props.selectedNodeId!], seed: mutations.length }); props.onProjectChange(result.project); props.onToast(`${id} created; the source branch remains untouched`) } catch (error) { props.onToast(error instanceof Error ? error.message : 'Mutation failed') } finally { setMutating(false) } }, 420) }
  function saveFirstInteraction() { const interaction = Object.values(state.interactions)[0]; if (!interaction) return props.onToast('Create an interaction before saving a recipe'); const recipe: FroamInteractionRecipe = { id: `recipe:${Date.now().toString(36)}`, name: interaction.name, interaction, bindings: { source: { role: 'trigger', originalNodeId: interaction.sourceId, required: true }, targets: interaction.targetIds.map((id, index) => ({ role: index ? `target-${index + 1}` : 'target', originalNodeId: id, required: true })) }, provenance: { kind: 'native', projectId: props.project.id, branchId: props.project.activeBranchId, createdAt: Date.now(), sourceInteractionId: interaction.id } }; saveLibrary(saveInteractionRecipe(library, recipe)) }
  async function sample() { if (!props.selectedElement || !props.selectedNodeId) return props.onToast('Select a Froam-controlled element to sample'); const rect = props.selectedElement.getBoundingClientRect(); let session = createSamplingSession({ id: `sample:${Date.now().toString(36)}`, trigger: 'click', sourceRole: 'trigger', startedAt: Date.now() }); session = recordSamplingFrame(session, { atMs: 0, targetRole: 'target', nodeId: props.selectedNodeId, styles: styles(props.selectedElement), geometry: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, visible: rect.width > 0 && rect.height > 0 }); await new Promise((resolve) => setTimeout(resolve, 240)); session = recordSamplingFrame(session, { atMs: 240, targetRole: 'target', nodeId: props.selectedNodeId, styles: styles(props.selectedElement), visible: true }); const recipe = samplingSessionToRecipe(session, { recipeId: `sampled:${Date.now().toString(36)}`, name: 'Observed interaction', projectId: props.project.id, branchId: props.project.activeBranchId }); saveLibrary(saveInteractionRecipe(library, recipe)); props.onToast('Observable frames saved as a sampled recipe') }
  function applyPhysics() { if (!props.selectedNodeId) return props.onToast('Select a node for Physics'); const base: FroamInteraction = Object.values(state.interactions)[0] ?? { id: `physics:${props.selectedNodeId}`, name: 'Physics spring', sourceId: props.selectedNodeId, targetIds: [props.selectedNodeId], trigger: 'drag', timeline: [{ at: 0, values: { transform: 'translate3d(0,0,0)' } }, { at: 1, values: { transform: 'translate3d(0,0,0)' } }] }; const interaction = interactionWithPhysics(base, spring); const event = createProjectEvent({ projectId: props.project.id, branchId: props.project.activeBranchId, actorId: props.actorId, clock: Math.max(0, ...props.project.events.map((item) => item.clock)) + 1, type: 'interaction.upserted', payload: { interaction }, targetIds: [props.selectedNodeId], label: 'Design Physics' }); props.onProjectChange((project) => appendProjectEvents(project, [event])); props.onToast('Deterministic spring compiled into FroamInteraction') }
  if (!props.open) return null
  return <aside className={`froam-labs ${mutating ? 'is-mutating' : ''}`} data-chef-editor-root="true"><header><div><Beaker size={16} /><strong>Froam Labs</strong><small>v8 prototypes · Experimental</small></div><button type="button" onClick={props.onClose}><X size={15} /></button></header><main>
    <section><h3>Independent flags</h3>{(Object.keys(flags) as Array<keyof FroamLabsFlags>).map((key) => <label className="froam-labs__flag" key={key}><input type="checkbox" checked={flags[key]} onChange={(event) => updateFlag(key, event.target.checked)} /><span>{key.replace(/[A-Z]/g, (letter) => ` ${letter}`).trim()}</span><em>Experimental</em></label>)}</section>
    <section className="froam-labs__mutate"><h3>☣ MUTATE</h3><p>Creates a branch-scoped deterministic proposal. The current source branch is never changed.</p><select value={level} onChange={(event) => setLevel(event.target.value as FroamMutationLevel)}><option value="safe">SAFE</option><option value="experimental">EXPERIMENTAL</option><option value="unhinged">UNHINGED</option></select><button type="button" disabled={!flags.mutate || mutating} onClick={mutate}>{mutating ? 'Energizing prototype…' : 'Create mutation branch'}</button>{mutations.at(-1) && <div className="froam-labs__compare"><span>Original<br/><b>{mutations.at(-1)!.sourceBranchId}</b></span><i>VS</i><span>Mutation<br/><b>{mutations.at(-1)!.id}</b></span></div>}</section>
    <section><h3><BookOpen size={14}/> Interaction Library</h3><button type="button" disabled={!flags.interactionLibrary} onClick={saveFirstInteraction}>Save existing interaction</button><ul>{Object.values(library).map((recipe) => <li key={recipe.id}><b>{recipe.name}</b><small>{recipe.provenance.kind} · {recipe.interaction.trigger}</small></li>)}</ul></section>
    <section><h3><Radio size={14}/> Native Sampler</h3><p>Records observable Froam-controlled DOM state only; it does not recover source implementation.</p><button type="button" disabled={!flags.uiSampling} onClick={() => void sample()}>Record observable frames</button></section>
    <section><h3><Atom size={14}/> Design Physics</h3>{(['stiffness','damping','mass'] as const).map((key) => <label key={key}>{key}<input type="number" value={spring[key]} onChange={(event) => setSpring({ ...spring, [key]: Number(event.target.value) })}/></label>)}<button type="button" disabled={!flags.designPhysics} onClick={applyPhysics}>Compile spring interaction</button></section>
  </main></aside>
}

