import type { FroamAsset, FroamInteraction } from './types'

export type FroamSoundCue = { assetId: string; offsetMs: number; volume: number; pitch: number; timing: 'start' | 'end' | 'keyframe'; keyframeAt?: number }
export type FroamSoundCollection = Record<string, FroamAsset>
export function importSoundAsset(collection: FroamSoundCollection, input: { id: string; name: string; url: string; mimeType: string; hash?: string; durationMs?: number }) { if (!input.mimeType.startsWith('audio/')) throw new Error('Froam Sound accepts audio assets only'); if (!/^(blob:|data:audio\/|https?:\/\/|\/)/.test(input.url)) throw new Error('Unsupported sound asset URL'); const asset: FroamAsset = { id: input.id, kind: 'audio', name: input.name.trim().slice(0, 100), url: input.url, mimeType: input.mimeType, hash: input.hash, metadata: { durationMs: input.durationMs, projectSound: true } }; return { ...collection, [asset.id]: asset } }
export function removeSoundAsset(collection: FroamSoundCollection, id: string, interactions: readonly FroamInteraction[] = []) { if (interactions.some((interaction) => interaction.feedback?.soundAssetId === id)) throw new Error('Detach this sound from interactions before removing it'); const next = { ...collection }; delete next[id]; return next }
export function attachSoundToInteraction(interaction: FroamInteraction, cue: Partial<FroamSoundCue> & { assetId: string }, collection: FroamSoundCollection): FroamInteraction { if (!collection[cue.assetId]) throw new Error('Unknown Froam sound asset'); const normalized = { assetId: cue.assetId, offsetMs: Math.max(0, cue.offsetMs ?? 0), volume: Math.max(0, Math.min(1, cue.volume ?? 1)), pitch: Math.max(.5, Math.min(2, cue.pitch ?? 1)), timing: cue.timing ?? 'start', keyframeAt: cue.keyframeAt }; return { ...interaction, feedback: { ...interaction.feedback, soundAssetId: normalized.assetId, soundOffsetMs: normalized.offsetMs, volume: normalized.volume, pitch: normalized.pitch }, metadata: { ...interaction.metadata, soundCue: normalized } } }
export function attachHapticIntent(interaction: FroamInteraction, haptic: NonNullable<FroamInteraction['feedback']>['haptic']) { return { ...interaction, feedback: { ...interaction.feedback, haptic }, metadata: { ...interaction.metadata, hapticPortableIntent: true, hapticGuarantee: 'platform-dependent' } } }
export function soundPreviewContract(asset: FroamAsset, input: { userGesture: boolean; volume?: number }) { if (!input.userGesture) throw new Error('Sound preview requires a user gesture because of browser autoplay policy'); return { assetId: asset.id, url: asset.url, volume: Math.max(0, Math.min(1, input.volume ?? 1)), autoplay: false, requiresUserGesture: true } }

