import type { FroamAnalysis, FroamInteraction, FroamProjectState } from './types'

export type FroamTrailerDuration = 10 | 15 | 30
export type FroamTrailerShot = { id: string; startMs: number; durationMs: number; kind: 'brand' | 'screen' | 'interaction' | 'component' | 'mutation' | 'mobile' | 'brand-end'; nodeId?: string; interactionId?: string; branchId?: string; label: string; viewport?: { width: number; height: number } }
export type FroamTrailerStoryboard = { id: string; durationSeconds: FroamTrailerDuration; createdAt: number; shots: FroamTrailerShot[]; source: { realProjectState: true; flowIds: string[]; branchId: string }; editable: true }
export interface FroamTrailerCaptureProvider { id: string; local: boolean; capture(input: { shot: FroamTrailerShot; state: FroamProjectState; interaction?: FroamInteraction }): Promise<{ shotId: string; frames: number; artifact?: Blob; limitations: string[] }> }
export function createTrailerStoryboard(input: { state: FroamProjectState; branchId: string; durationSeconds: FroamTrailerDuration; now?: number; selectedNodeIds?: string[]; mutationBranchId?: string }) { const durationMs = input.durationSeconds * 1000; const candidates = input.selectedNodeIds?.length ? input.selectedNodeIds : Object.values(input.state.flows).flatMap((flow) => flow.nodeIds); const nodes = [...new Set(candidates)].filter((id) => input.state.nodes[id]); const interactions = Object.values(input.state.interactions).filter((interaction) => nodes.includes(interaction.sourceId) || interaction.targetIds.some((id) => nodes.includes(id))); const raw: Omit<FroamTrailerShot, 'startMs' | 'durationMs'>[] = [{ id: 'brand-open', kind: 'brand', label: 'Brand opening' }, ...nodes.slice(0, input.durationSeconds === 10 ? 2 : input.durationSeconds === 15 ? 3 : 6).map((nodeId, index) => ({ id: `screen-${index}`, kind: 'screen' as const, nodeId, label: input.state.nodes[nodeId].name ?? `Screen ${index + 1}` })), ...interactions.slice(0, 2).map((interaction, index) => ({ id: `interaction-${index}`, kind: 'interaction' as const, interactionId: interaction.id, nodeId: interaction.sourceId, label: interaction.name })), ...(input.mutationBranchId ? [{ id: 'mutation', kind: 'mutation' as const, branchId: input.mutationBranchId, label: 'Mutation prototype' }] : []), { id: 'mobile', kind: 'mobile', label: 'Mobile state' }, { id: 'brand-end', kind: 'brand-end', label: 'Brand end' }]; const shotDuration = durationMs / Math.max(1, raw.length); const shots = raw.map((shot, index) => ({ ...shot, startMs: Math.round(index * shotDuration), durationMs: Math.round(shotDuration), ...(shot.kind === 'mobile' ? { viewport: { width: 390, height: 844 } } : {}) })); const storyboard: FroamTrailerStoryboard = { id: `trailer:${input.now ?? Date.now()}`, durationSeconds: input.durationSeconds, createdAt: input.now ?? Date.now(), shots, source: { realProjectState: true, flowIds: Object.keys(input.state.flows), branchId: input.branchId }, editable: true }; return storyboard }
export function reorderTrailerShot(storyboard: FroamTrailerStoryboard, shotId: string, toIndex: number) { const shots = [...storyboard.shots]; const from = shots.findIndex((shot) => shot.id === shotId); if (from < 0) return storyboard; const [shot] = shots.splice(from, 1); shots.splice(Math.max(0, Math.min(shots.length, toIndex)), 0, shot); const durationMs = storyboard.durationSeconds * 1000 / shots.length; return { ...storyboard, shots: shots.map((item, index) => ({ ...item, startMs: Math.round(index * durationMs), durationMs: Math.round(durationMs) })) } }
export function removeTrailerShot(storyboard: FroamTrailerStoryboard, shotId: string) { const shots = storyboard.shots.filter((shot) => shot.id !== shotId); if (!shots.length) throw new Error('A trailer needs at least one real product shot'); return reorderTrailerShot({ ...storyboard, shots }, shots[0].id, 0) }
export function trailerStoryboardAnalysis(storyboard: FroamTrailerStoryboard): FroamAnalysis { return { schemaVersion: 1, id: storyboard.id, kind: 'trailer-storyboard', targetIds: storyboard.shots.map((shot) => shot.nodeId).filter((id): id is string => Boolean(id)), createdAt: storyboard.createdAt, provider: 'froam-real-state-storyboard-v1', local: true, confidence: 1, result: structuredClone(storyboard) as unknown as Record<string, unknown> } }

