import type { FroamInteractionRecipe } from './interaction-library'

export type FroamObservedStyle = Record<string, string | number>
export type FroamSampleFrame = { atMs: number; targetRole: string; nodeId?: string; styles: FroamObservedStyle; geometry?: { x: number; y: number; width: number; height: number }; visible?: boolean; scroll?: { x: number; y: number }; animation?: { name?: string; durationMs?: number; easing?: string } }
export type FroamSamplingObservation = { atMs: number; type: 'event' | 'mutation' | 'frame'; targetRole: string; detail: Record<string, unknown> }
export type FroamSamplingSession = { id: string; trigger: string; sourceRole: string; startedAt: number; frames: FroamSampleFrame[]; observations: FroamSamplingObservation[]; provenance: 'froam-controlled-dom'; unsupportedEffects: string[] }
export type FroamSamplingTimelineEntry = { atMs: number; label: string; kind: FroamSamplingObservation['type']; targetRole: string }
export function createSamplingSession(input: Omit<FroamSamplingSession, 'frames' | 'observations' | 'provenance' | 'unsupportedEffects'>): FroamSamplingSession { return { ...input, frames: [], observations: [], provenance: 'froam-controlled-dom', unsupportedEffects: [] } }
export function recordSamplingFrame(session: FroamSamplingSession, frame: FroamSampleFrame): FroamSamplingSession { const cloned = structuredClone(frame); const observation: FroamSamplingObservation = { atMs: frame.atMs, type: 'frame', targetRole: frame.targetRole, detail: { nodeId: frame.nodeId, styles: Object.keys(frame.styles), geometry: frame.geometry, visible: frame.visible } }; return { ...session, frames: [...session.frames, cloned].sort((a, b) => a.atMs - b.atMs), observations: [...session.observations, observation].sort((a, b) => a.atMs - b.atMs) } }
export function recordSamplingEvent(session: FroamSamplingSession, input: { atMs: number; targetRole: string; event: string; key?: string; pointerType?: string }): FroamSamplingSession { const observation: FroamSamplingObservation = { atMs: input.atMs, type: 'event', targetRole: input.targetRole, detail: { event: input.event, key: input.key, pointerType: input.pointerType } }; return { ...session, observations: [...session.observations, observation].sort((a, b) => a.atMs - b.atMs) } }
export function recordSamplingMutation(session: FroamSamplingSession, input: { atMs: number; targetRole: string; kind: 'attributes' | 'child-list' | 'visibility'; attributeName?: string; added?: number; removed?: number }): FroamSamplingSession { const observation: FroamSamplingObservation = { atMs: input.atMs, type: 'mutation', targetRole: input.targetRole, detail: { kind: input.kind, attributeName: input.attributeName, added: input.added, removed: input.removed } }; return { ...session, observations: [...session.observations, observation].sort((a, b) => a.atMs - b.atMs) } }
export function addUnsupportedSamplingEffect(session: FroamSamplingSession, effect: string) { return { ...session, unsupportedEffects: [...new Set([...session.unsupportedEffects, effect])] } }

const OBSERVED_STYLE_FIELDS = ['opacity', 'transform', 'visibility', 'display', 'filter', 'backdropFilter', 'color', 'backgroundColor', 'borderRadius', 'width', 'height', 'left', 'top', 'position'] as const
export function captureElementFrame(element: HTMLElement, input: { atMs: number; targetRole: string; nodeId?: string }): FroamSampleFrame { const computed = getComputedStyle(element); const rect = element.getBoundingClientRect(); const styles = Object.fromEntries(OBSERVED_STYLE_FIELDS.map((field) => [field, computed[field as keyof CSSStyleDeclaration] as string]).filter(([, value]) => value !== '' && value !== undefined)); const animations = element.getAnimations?.() ?? []; const timing = animations[0]?.effect?.getTiming(); return { ...input, styles, geometry: { x: rect.x, y: rect.y, width: rect.width, height: rect.height }, visible: computed.visibility !== 'hidden' && computed.display !== 'none' && rect.width > 0 && rect.height > 0, scroll: { x: element.scrollLeft, y: element.scrollTop }, ...(animations.length ? { animation: { durationMs: typeof timing?.duration === 'number' ? timing.duration : undefined, easing: timing?.easing } } : {}) } }

export function createNativeSamplingRecorder(input: { root: HTMLElement; targets: Array<{ element: HTMLElement; role: string; nodeId?: string }>; trigger: string; sourceRole: string; now?: () => number; frameIntervalMs?: number }) {
  const now = input.now ?? (() => performance.now()); const startedAt = now(); let session = createSamplingSession({ id: `sample:${Math.round(startedAt).toString(36)}`, trigger: input.trigger, sourceRole: input.sourceRole, startedAt }); let timer: number | undefined; let observer: MutationObserver | undefined; const listeners: Array<() => void> = []
  const elapsed = () => Math.max(0, now() - startedAt); const roleFor = (target: EventTarget | null) => input.targets.find((item) => target instanceof Node && item.element.contains(target))?.role ?? input.sourceRole
  const snapshot = () => { for (const target of input.targets) session = recordSamplingFrame(session, captureElementFrame(target.element, { atMs: elapsed(), targetRole: target.role, nodeId: target.nodeId })) }
  return { start() { snapshot(); for (const type of ['pointerdown', 'click', 'keydown', 'focusin', 'scroll']) { const listener = (event: Event) => { session = recordSamplingEvent(session, { atMs: elapsed(), targetRole: roleFor(event.target), event: type, key: event instanceof KeyboardEvent ? event.key : undefined, pointerType: event instanceof PointerEvent ? event.pointerType : undefined }); snapshot() }; input.root.addEventListener(type, listener, true); listeners.push(() => input.root.removeEventListener(type, listener, true)) } if (typeof MutationObserver !== 'undefined') { observer = new MutationObserver((mutations) => { for (const mutation of mutations) session = recordSamplingMutation(session, { atMs: elapsed(), targetRole: roleFor(mutation.target), kind: mutation.type === 'childList' ? 'child-list' : 'attributes', attributeName: mutation.attributeName ?? undefined, added: mutation.type === 'childList' ? mutation.addedNodes.length : undefined, removed: mutation.type === 'childList' ? mutation.removedNodes.length : undefined }); snapshot() }); observer.observe(input.root, { subtree: true, attributes: true, childList: true, attributeFilter: ['class', 'style', 'hidden', 'open', 'aria-expanded'] }) } timer = window.setInterval(snapshot, Math.max(16, input.frameIntervalMs ?? 50)); return this }, stop() { if (timer !== undefined) window.clearInterval(timer); observer?.disconnect(); listeners.splice(0).forEach((remove) => remove()); snapshot(); return structuredClone(session) }, session: () => structuredClone(session) }
}

export function samplingTimeline(session: FroamSamplingSession): FroamSamplingTimelineEntry[] { return session.observations.map((item) => ({ atMs: item.atMs, kind: item.type, targetRole: item.targetRole, label: item.type === 'event' ? `${String(item.detail.event)} ${item.targetRole}` : item.type === 'mutation' ? `${String(item.detail.kind)} ${item.targetRole}` : `State ${item.targetRole}` })) }
export function trimSamplingSession(session: FroamSamplingSession, startMs: number, endMs: number): FroamSamplingSession { const low = Math.max(0, Math.min(startMs, endMs)); const high = Math.max(low + 1, Math.max(startMs, endMs)); const shift = <T extends { atMs: number }>(items: T[]) => items.filter((item) => item.atMs >= low && item.atMs <= high).map((item) => ({ ...item, atMs: item.atMs - low })); return { ...session, startedAt: session.startedAt + low, frames: shift(session.frames), observations: shift(session.observations) } }
export function samplingSessionToRecipe(session: FroamSamplingSession, input: { recipeId: string; name: string; projectId: string; branchId: string; confidence?: number }): FroamInteractionRecipe {
  if (!session.frames.length) throw new Error('A sampled interaction needs observable frames')
  const roles = [...new Set(session.frames.map((frame) => frame.targetRole))]; const duration = Math.max(1, ...session.frames.map((frame) => frame.atMs)); const targetRole = roles[0]; const timeline = session.frames.filter((frame) => frame.targetRole === targetRole).map((frame) => ({ at: frame.atMs / duration, values: { ...frame.styles, ...(frame.visible === undefined ? {} : { visibility: frame.visible ? 'visible' : 'hidden' }), ...(frame.geometry ? { x: frame.geometry.x, y: frame.geometry.y, width: frame.geometry.width, height: frame.geometry.height } : {}) } }))
  return { id: input.recipeId, name: input.name, category: session.trigger === 'scroll' ? 'Scroll' : 'Sampled', interaction: { id: input.recipeId, name: input.name, sourceId: `role:${session.sourceRole}`, targetIds: roles.map((role) => `role:${role}`), trigger: session.trigger === 'hover' ? 'hover' : session.trigger === 'focus' ? 'focus' : session.trigger === 'scroll' ? 'scroll' : 'click', timeline, durationMs: duration, metadata: { reconstructedFromObservation: true, observedFrameCount: session.frames.length, observationCount: session.observations.length, sampledTimeline: samplingTimeline(session) } }, bindings: { source: { role: session.sourceRole, required: true }, targets: roles.map((role) => ({ role, required: true })) }, provenance: { kind: 'sampled', source: 'froam', projectId: input.projectId, branchId: input.branchId, createdAt: session.startedAt, provider: 'froam-native-sampler-v2', confidence: input.confidence ?? Math.min(.95, .5 + Math.min(1, session.frames.length / 12) * .35 - session.unsupportedEffects.length * .05), unsupportedEffects: session.unsupportedEffects, originalImplementation: 'unknown' } }
}
