/**
 * Froam Studio v3 — shared codegen.
 *
 * Single source of truth for everything that turns froam.design.json
 * into shippable artifacts. Used by the Vite plugin, the `froam` CLI,
 * and the universal dev bridge so every integration produces
 * identical output:
 *
 *   froam.design.json     — canonical design store (v3)
 *   froam.generated.css   — styles compiled to static CSS
 *   froam.runtime.js      — zero-dependency vanilla runtime (text /
 *                           image / injected-block drafts for sites
 *                           that don't mount the React FroamRuntime)
 */
import fs from 'node:fs'
import path from 'node:path'

export const DESIGN_VERSION = 3
export const CANVAS_KEY = '__froam_canvas__'
export const INJECTION_KEY = '__froam_injection__'
export const VIEWPORTS = ['desktop', 'tablet', 'mobile']
export const MEDIA = {
  desktop: '@media (min-width: 1025px)',
  tablet: '@media (min-width: 641px) and (max-width: 1024px)',
  mobile: '@media (max-width: 640px)',
}

export function emptyDesign() {
  return {
    version: DESIGN_VERSION,
    updatedAt: null,
    meta: { createdWith: 'froam-studio@3' },
    routes: {},
  }
}

/** Accepts any v1/v2/v3 design object and returns a valid v3 design. */
export function migrateDesign(design) {
  if (!design || typeof design !== 'object' || typeof design.routes !== 'object' || design.routes === null) {
    return emptyDesign()
  }
  return {
    ...design,
    version: DESIGN_VERSION,
    meta: { createdWith: 'froam-studio@3', ...(design.meta ?? {}) },
    routes: design.routes,
  }
}

export function loadDesign(designPath) {
  try {
    const parsed = JSON.parse(fs.readFileSync(designPath, 'utf8'))
    if (parsed && typeof parsed === 'object' && parsed.routes) return migrateDesign(parsed)
  } catch {
    /* fall through to empty */
  }
  return emptyDesign()
}

function camelToKebab(value) {
  return value.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
}

function cssEscapeAttr(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

function isSpecialPath(draftPath) {
  return draftPath === CANVAS_KEY || draftPath.startsWith(`${INJECTION_KEY}:`) || draftPath.startsWith('__froam')
}

function pathToSelector(draftPath) {
  const segments = draftPath.split('/').filter(Boolean)
  const parts = []
  for (const segment of segments) {
    const [tag, indexRaw] = segment.split(':')
    const index = Number(indexRaw)
    if (!tag || !/^[a-z][a-z0-9-]*$/i.test(tag) || !Number.isInteger(index) || index < 1) return null
    parts.push(`${tag.toLowerCase()}:nth-of-type(${index})`)
  }
  if (!parts.length) return null
  return `:where([data-froam-root], #root, #__next) > ${parts.join(' > ')}`
}

function declarations(styles, indent) {
  const lines = []
  for (const [key, value] of Object.entries(styles ?? {})) {
    if (key === 'customCSS' || value === '' || value == null) continue
    lines.push(`${indent}${camelToKebab(key)}: ${value} !important;`)
  }
  return lines
}

export function generateCss(design) {
  const out = [
    '/* Generated by froam-studio (Repo Mode) — do not edit by hand.',
    '   Edit visually in the Froam editor, then "Save to Repo". */',
    '',
  ]
  const customCssBlocks = []

  for (const [routeKey, viewports] of Object.entries(design.routes ?? {})) {
    for (const viewport of VIEWPORTS) {
      const store = viewports?.[viewport]
      if (!store || !Object.keys(store).length) continue
      const scope = `html[data-froam-route="${cssEscapeAttr(routeKey)}"]:not([data-chef-editing])`
      const rules = []

      for (const [draftPath, draft] of Object.entries(store)) {
        if (draftPath === CANVAS_KEY) {
          const decls = declarations(draft?.styles, '    ')
          if (decls.length) rules.push(`  ${scope} [data-froam-canvas] {\n${decls.join('\n')}\n  }`)
          if (draft?.styles?.customCSS) customCssBlocks.push(draft.styles.customCSS)
          continue
        }
        if (isSpecialPath(draftPath) || !draft?.styles) continue
        const selector = pathToSelector(draftPath)
        if (!selector) continue
        const decls = declarations(draft.styles, '    ')
        if (!decls.length) continue
        rules.push(`  ${scope} ${selector} {\n${decls.join('\n')}\n  }`)
      }

      if (!rules.length) continue
      out.push(`/* ── ${routeKey} · ${viewport} ── */`)
      out.push(`${MEDIA[viewport]} {`)
      out.push(rules.join('\n\n'))
      out.push('}')
      out.push('')
    }
  }

  if (customCssBlocks.length) {
    out.push('/* ── Custom CSS (canvas) ── */')
    out.push(customCssBlocks.join('\n\n'))
    out.push('')
  }

  return out.join('\n')
}

/**
 * Vanilla production runtime — applies the parts of a design that pure
 * CSS can't express (text edits, image swaps, injected blocks, custom
 * canvas CSS) on any website with zero dependencies. The design is
 * inlined so the file is self-contained and cache-friendly.
 */
export function generateRuntimeJs(design) {
  const routes = {}
  for (const [routeKey, viewports] of Object.entries(design.routes ?? {})) {
    const slim = {}
    for (const viewport of VIEWPORTS) {
      const store = viewports?.[viewport]
      if (!store) continue
      const kept = {}
      for (const [draftPath, draft] of Object.entries(store)) {
        if (!draft) continue
        const entry = {}
        if (draftPath === CANVAS_KEY) {
          if (draft.styles?.customCSS) entry.customCSS = draft.styles.customCSS
        } else if (draftPath.startsWith(`${INJECTION_KEY}:`)) {
          if (draft.text !== undefined) entry.text = draft.text
        } else {
          if (draft.text !== undefined) entry.text = draft.text
          if (draft.imageUrl !== undefined) entry.imageUrl = draft.imageUrl
        }
        if (Object.keys(entry).length) kept[draftPath] = entry
      }
      if (Object.keys(kept).length) slim[viewport] = kept
    }
    if (Object.keys(slim).length) routes[routeKey] = slim
  }

  const designJson = JSON.stringify({ version: design.version ?? DESIGN_VERSION, routes })

  return `/* Generated by froam-studio (Repo Mode) — do not edit by hand.
   Zero-dependency Froam runtime: route attribute + text/image/injected
   drafts for sites that don't mount the React <FroamRuntime/>. */
;(function () {
  'use strict'
  if (typeof window === 'undefined' || typeof document === 'undefined') return
  if (window.__FROAM_VANILLA_RUNTIME__) return
  window.__FROAM_VANILLA_RUNTIME__ = true

  var DESIGN = ${designJson}
  var CANVAS_KEY = '${CANVAS_KEY}'
  var INJECTION_PREFIX = '${INJECTION_KEY}:'
  var ROOT_PARENT_KEY = '__froam_root__'
  var TEXT_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span', 'small', 'strong', 'em', 'b', 'i', 'label', 'button', 'a', 'li']

  function getRoot() {
    return (
      document.querySelector('[data-froam-root]') ||
      document.getElementById('root') ||
      document.getElementById('__next') ||
      document.querySelector('main') ||
      document.body
    )
  }

  function viewportMode() {
    if (window.matchMedia('(max-width: 640px)').matches) return 'mobile'
    if (window.matchMedia('(max-width: 1024px)').matches) return 'tablet'
    return 'desktop'
  }

  function findByPath(root, pathValue) {
    var segments = pathValue.split('/').filter(Boolean)
    var current = root
    for (var i = 0; i < segments.length; i += 1) {
      var pieces = segments[i].split(':')
      var tag = pieces[0]
      var index = Number(pieces[1]) - 1
      if (!tag || isNaN(index) || index < 0 || !current) return null
      var matches = []
      for (var c = 0; c < current.children.length; c += 1) {
        var child = current.children[c]
        if (child.tagName && child.tagName.toLowerCase() === tag) matches.push(child)
      }
      current = matches[index] || null
    }
    return current
  }

  function canApplyText(element) {
    var tag = element.tagName.toLowerCase()
    if (tag === 'input' || tag === 'textarea') return false
    if (element.children.length === 0) return true
    return TEXT_TAGS.indexOf(tag) !== -1
  }

  function clearInjected(root) {
    var injected = root.querySelectorAll('[data-froam-runtime-injected="true"]')
    for (var i = 0; i < injected.length; i += 1) injected[i].parentNode.removeChild(injected[i])
  }

  function applyInjections(root, store) {
    var blocks = []
    for (var key in store) {
      if (key.indexOf(INJECTION_PREFIX) !== 0 || !store[key].text) continue
      try {
        var parsed = JSON.parse(store[key].text)
        if (typeof parsed.html === 'string' && typeof parsed.parentPath === 'string') {
          blocks.push({ html: parsed.html, parentPath: parsed.parentPath, order: typeof parsed.order === 'number' ? parsed.order : 0 })
        }
      } catch (e) { /* skip malformed */ }
    }
    blocks.sort(function (a, b) { return a.order - b.order })
    for (var i = 0; i < blocks.length; i += 1) {
      var parent = blocks[i].parentPath === ROOT_PARENT_KEY ? root : findByPath(root, blocks[i].parentPath)
      if (!parent) continue
      var template = document.createElement('template')
      template.innerHTML = blocks[i].html.trim()
      var node = template.content.firstElementChild
      if (!node) continue
      node.setAttribute('data-froam-runtime-injected', 'true')
      node.removeAttribute('data-chef-selected')
      node.removeAttribute('data-chef-hovered')
      parent.appendChild(node)
    }
  }

  function applyCustomCss(css) {
    var styleEl = document.getElementById('froam-global-styles')
    if (css) {
      if (!styleEl) {
        styleEl = document.createElement('style')
        styleEl.id = 'froam-global-styles'
        document.head.appendChild(styleEl)
      }
      if (styleEl.textContent !== css) styleEl.textContent = css
    } else if (styleEl) {
      styleEl.textContent = ''
    }
  }

  function apply() {
    if (document.documentElement.hasAttribute('data-chef-editing')) return
    var routeKey = window.location.pathname || '/'
    document.documentElement.setAttribute('data-froam-route', routeKey)

    var root = getRoot()
    if (!root) return
    if (!root.hasAttribute('data-froam-root')) root.setAttribute('data-froam-root', '')

    clearInjected(root)
    var route = DESIGN.routes[routeKey]
    var store = route && route[viewportMode()]
    if (!store) { applyCustomCss(''); return }

    applyInjections(root, store)

    for (var key in store) {
      if (key === CANVAS_KEY) { applyCustomCss(store[key].customCSS || ''); continue }
      if (key.indexOf('__froam') === 0) continue
      var target = findByPath(root, key)
      if (!target) continue
      var draft = store[key]
      if (draft.text !== undefined && canApplyText(target) && target.innerText !== draft.text) {
        target.innerText = draft.text
      }
      if (draft.imageUrl !== undefined && target.tagName.toLowerCase() === 'img') {
        if (draft.imageUrl && target.getAttribute('src') !== draft.imageUrl) target.src = draft.imageUrl
        if (!draft.imageUrl && target.hasAttribute('src')) target.removeAttribute('src')
      }
    }
  }

  var frame = 0
  function scheduleApply() {
    cancelAnimationFrame(frame)
    frame = requestAnimationFrame(apply)
  }

  function patchHistory(method) {
    var original = window.history[method]
    window.history[method] = function () {
      var result = original.apply(this, arguments)
      scheduleApply()
      return result
    }
  }

  function start() {
    apply()
    patchHistory('pushState')
    patchHistory('replaceState')
    window.addEventListener('popstate', scheduleApply)
    window.addEventListener('resize', scheduleApply)
    var root = getRoot()
    if (root && typeof MutationObserver !== 'undefined') {
      var observer = new MutationObserver(function (mutations) {
        for (var i = 0; i < mutations.length; i += 1) {
          var node = mutations[i].target
          if (node && node.closest && node.closest('[data-froam-runtime-injected="true"], [data-chef-editor-root]')) continue
          scheduleApply()
          return
        }
      })
      observer.observe(root, { childList: true, subtree: true })
    }
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start)
  else start()
})()
`
}

const GLUE_TS = `// Generated by froam-studio — do not edit by hand.
import './froam.generated.css'
import design from './froam.design.json'
export default design
`

/**
 * Ensure the froam dir exists with design.json / generated.css /
 * runtime.js (+ index.ts glue when `glue` is true, for bundled
 * React/Vite apps that import the design).
 */
export function ensureScaffold(froamDir, { glue = true } = {}) {
  fs.mkdirSync(froamDir, { recursive: true })
  const designPath = path.join(froamDir, 'froam.design.json')
  if (!fs.existsSync(designPath)) {
    fs.writeFileSync(designPath, JSON.stringify(emptyDesign(), null, 2) + '\n')
  }
  const design = loadDesign(designPath)
  const cssPath = path.join(froamDir, 'froam.generated.css')
  if (!fs.existsSync(cssPath)) fs.writeFileSync(cssPath, generateCss(design))
  const runtimePath = path.join(froamDir, 'froam.runtime.js')
  if (!fs.existsSync(runtimePath)) fs.writeFileSync(runtimePath, generateRuntimeJs(design))
  if (glue) {
    const gluePath = path.join(froamDir, 'index.ts')
    if (!fs.existsSync(gluePath)) fs.writeFileSync(gluePath, GLUE_TS)
  }
  return design
}

/** Compile design.json → generated.css + runtime.js. Returns file list. */
export function writeArtifacts(froamDir, design) {
  fs.writeFileSync(path.join(froamDir, 'froam.design.json'), JSON.stringify(design, null, 2) + '\n')
  fs.writeFileSync(path.join(froamDir, 'froam.generated.css'), generateCss(design))
  fs.writeFileSync(path.join(froamDir, 'froam.runtime.js'), generateRuntimeJs(design))
  return ['froam.design.json', 'froam.generated.css', 'froam.runtime.js']
}

/** Merge one route+viewport store into a design (repo save payload). */
export function mergeSave(design, { routeKey, viewportMode, store }) {
  const next = migrateDesign(design)
  next.routes[routeKey] = next.routes[routeKey] ?? {}
  next.routes[routeKey][viewportMode] = store
  next.updatedAt = new Date().toISOString()
  return next
}
