/* Generated by froam-studio (Repo Mode) — do not edit by hand.
   Zero-dependency Froam runtime: route attribute + text/image/injected
   drafts for sites that don't mount the React <FroamRuntime/>. */
;(function () {
  'use strict'
  if (typeof window === 'undefined' || typeof document === 'undefined') return
  if (window.__FROAM_VANILLA_RUNTIME__) return
  window.__FROAM_VANILLA_RUNTIME__ = true

  var DESIGN = {"version":3,"routes":{}}
  var CANVAS_KEY = '__froam_canvas__'
  var INJECTION_PREFIX = '__froam_injection__:'
  var ROOT_PARENT_KEY = '__froam_root__'
  var TEXT_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span', 'small', 'strong', 'em', 'b', 'i', 'label', 'button', 'a', 'li']

  function getRoot() {
    return (
      document.querySelector('[data-froam-root]') ||
      document.getElementById('root') ||
      document.getElementById('__next') ||
      document.querySelector('main') ||
      document.body
    )
  }

  function viewportMode() {
    if (window.matchMedia('(max-width: 640px)').matches) return 'mobile'
    if (window.matchMedia('(max-width: 1024px)').matches) return 'tablet'
    return 'desktop'
  }

  function findByPath(root, pathValue) {
    var segments = pathValue.split('/').filter(Boolean)
    var current = root
    for (var i = 0; i < segments.length; i += 1) {
      var pieces = segments[i].split(':')
      var tag = pieces[0]
      var index = Number(pieces[1]) - 1
      if (!tag || isNaN(index) || index < 0 || !current) return null
      var matches = []
      for (var c = 0; c < current.children.length; c += 1) {
        var child = current.children[c]
        if (child.tagName && child.tagName.toLowerCase() === tag) matches.push(child)
      }
      current = matches[index] || null
    }
    return current
  }

  function canApplyText(element) {
    var tag = element.tagName.toLowerCase()
    if (tag === 'input' || tag === 'textarea') return false
    if (element.children.length === 0) return true
    return TEXT_TAGS.indexOf(tag) !== -1
  }

  function clearInjected(root) {
    var injected = root.querySelectorAll('[data-froam-runtime-injected="true"]')
    for (var i = 0; i < injected.length; i += 1) injected[i].parentNode.removeChild(injected[i])
  }

  function applyInjections(root, store) {
    var blocks = []
    for (var key in store) {
      if (key.indexOf(INJECTION_PREFIX) !== 0 || !store[key].text) continue
      try {
        var parsed = JSON.parse(store[key].text)
        if (typeof parsed.html === 'string' && typeof parsed.parentPath === 'string') {
          blocks.push({ html: parsed.html, parentPath: parsed.parentPath, order: typeof parsed.order === 'number' ? parsed.order : 0 })
        }
      } catch (e) { /* skip malformed */ }
    }
    blocks.sort(function (a, b) { return a.order - b.order })
    for (var i = 0; i < blocks.length; i += 1) {
      var parent = blocks[i].parentPath === ROOT_PARENT_KEY ? root : findByPath(root, blocks[i].parentPath)
      if (!parent) continue
      var template = document.createElement('template')
      template.innerHTML = blocks[i].html.trim()
      var node = template.content.firstElementChild
      if (!node) continue
      node.setAttribute('data-froam-runtime-injected', 'true')
      node.removeAttribute('data-chef-selected')
      node.removeAttribute('data-chef-hovered')
      parent.appendChild(node)
    }
  }

  function applyCustomCss(css) {
    var styleEl = document.getElementById('froam-global-styles')
    if (css) {
      if (!styleEl) {
        styleEl = document.createElement('style')
        styleEl.id = 'froam-global-styles'
        document.head.appendChild(styleEl)
      }
      if (styleEl.textContent !== css) styleEl.textContent = css
    } else if (styleEl) {
      styleEl.textContent = ''
    }
  }

  function normRoute(value) {
    var p = String(value || '/').split('?')[0].split('#')[0]
    p = p.replace(/\/index\.html?$/i, '/')
    p = p.replace(/\/+$/, '')
    return p || '/'
  }

  function apply() {
    if (document.documentElement.hasAttribute('data-chef-editing')) return
    var routeKey = normRoute(window.location.pathname)
    document.documentElement.setAttribute('data-froam-route', routeKey)

    var root = getRoot()
    if (!root) return
    if (!root.hasAttribute('data-froam-root')) root.setAttribute('data-froam-root', '')

    clearInjected(root)
    var route = DESIGN.routes[routeKey]
    var store = route && route[viewportMode()]
    if (!store) { applyCustomCss(''); return }

    applyInjections(root, store)

    for (var key in store) {
      if (key === CANVAS_KEY) { applyCustomCss(store[key].customCSS || ''); continue }
      if (key.indexOf('__froam') === 0) continue
      var target = findByPath(root, key)
      if (!target) continue
      var draft = store[key]
      if (draft.text !== undefined && canApplyText(target) && target.innerText !== draft.text) {
        target.innerText = draft.text
      }
      if (draft.imageUrl !== undefined && target.tagName.toLowerCase() === 'img') {
        if (draft.imageUrl && target.getAttribute('src') !== draft.imageUrl) target.src = draft.imageUrl
        if (!draft.imageUrl && target.hasAttribute('src')) target.removeAttribute('src')
      }
    }
  }

  var frame = 0
  function scheduleApply() {
    cancelAnimationFrame(frame)
    frame = requestAnimationFrame(apply)
  }

  function patchHistory(method) {
    var original = window.history[method]
    window.history[method] = function () {
      var result = original.apply(this, arguments)
      scheduleApply()
      return result
    }
  }

  function start() {
    apply()
    patchHistory('pushState')
    patchHistory('replaceState')
    window.addEventListener('popstate', scheduleApply)
    window.addEventListener('resize', scheduleApply)
    var root = getRoot()
    if (root && typeof MutationObserver !== 'undefined') {
      var observer = new MutationObserver(function (mutations) {
        for (var i = 0; i < mutations.length; i += 1) {
          var node = mutations[i].target
          if (node && node.closest && node.closest('[data-froam-runtime-injected="true"], [data-chef-editor-root]')) continue
          scheduleApply()
          return
        }
      })
      observer.observe(root, { childList: true, subtree: true })
    }
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start)
  else start()
})()
